### PR TITLE
Fix a crash when the url doesn't contain a protocol

### LINKED ISSUE #112: Crash when not specifying a protocol
**Describe the bug**

When only specifying an ip address without a protocoll, odd crashes  with
```shell
Started with PID 24241
URL specified: 127.0.0.1
URL fixed    : http://127.0.0.1/
Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at OpenDirectoryDownloader.Program.Main(String[] args) in [REMOVED_PATH]/OpenDirectoryDownloader/src/OpenDirectoryDownloader/Program.cs:line 124
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
fish: Job 1, './bin/OpenDirectoryDownloader -…' terminated by signal SIGABRT (Abort)
```

**To Reproduce**
`OpenDirectoryDownloader --url 127.0.0.1`

**Expected behavior**

No crash

**Desktop (please complete the following information):**
 - OS: linux
 - Version: current master: 5d0765ff

### PR DESCRIPTION
**Pull request by 4censord**
Us the `fixed` url that is created earlier via the `Library.FixUrl(url)` method.

This fixes #112

### CODE REVIEW

**Comment by 4censord** [comment]
Two tests are failing, 
* TestDirectoryListing65aAsync
* TestDirectoryListing65bAsync
But they have been failing since c251541caab81e82511088cd43bd4e185292cf78
so no difference to before.

**Comment by KoalaBear84** [comment]
I'll take a look at this ASAP. Normally I do respond quick, and I saw @Chaphasilor already handling it 😅😂

**Comment by Chaphasilor** [comment]
Sorry, I was planning to look into it, but didn't get around to it.  
Good job noticing that there already is a fixed URL!

**Comment by KoalaBear84** [comment]
> Two tests are failing,
> 
> * TestDirectoryListing65aAsync
> * TestDirectoryListing65bAsync
> 
> But they have been failing since [c251541](https://github.com/KoalaBear84/OpenDirectoryDownloader/commit/c251541caab81e82511088cd43bd4e185292cf78) so no difference to before.

Thanks, didn't knew, thanks for mentioning 👍

**Review by KoalaBear84 — APPROVED** [review]

**Comment by KoalaBear84** [comment]
Thanks! Merged.

**Pull request merged**
