### PR TITLE
Fix Warning SYSLIB0013: EscapeUriString is obsolete

### PR DESCRIPTION
**Pull request by 4censord**
Building with dotnet version 6.0.100 gives 4 warnings:
```
src/OpenDirectoryDownloader/UrlEncodingParser.cs(124,23): 
warning SYSLIB0013: 'Uri.EscapeUriString(string)' is obsolete: 
'Uri.EscapeUriString can corrupt the Uri string in some cases. Consider using Uri.EscapeDataString for query string components.'
```

According to the documentation:

>The Uri.EscapeUriString(String) API is marked as obsolete, starting in .NET
> 6. Using it in code generates warning SYSLIB0013 at compile time.
> Uri.EscapeUriString(String) can corrupt the Uri string in some cases.

~ https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0013
~ https://github.com/dotnet/runtime/issues/31387

### CODE REVIEW

**Review by Chaphasilor — APPROVED** [review]
Looking at the docs it seems like both functions really do the same, with the old one just having some hiccups every now and then.  
Doesn't look like there's any "intended behavior" being used that would cause a breaking change 😁

**Comment by KoalaBear84** [comment]
Thanks for the PR.

Yes, correct. I've tried to replace it before. But when you do, some test fails, and didn't find a good replacement. Also didn't fully investigate the issue behind it.

Do some test also fail over there?

**Comment by 4censord** [comment]
Indeed 3 tests failed.

All 3 of those had already partly encoded urls.

https://thetrove.net/Assets/D&D%20Homebrew/index.html
                               ^
Decoding those urls fixes the tests.

**Comment by 4censord** [comment]
Just for reference; the test that failed are:
* TestDirectoryListing13cAsync
* TestDirectoryListing13bAsync
* TestDirectoryListing101aAsync

**Comment by KoalaBear84** [comment]
I see, thanks! I'll check on it hopefully this evening :)

**Comment by Chaphasilor** [comment]
> Indeed 3 tests failed.
> 
> All 3 of those had already partly encoded urls.
> ```
> https://thetrove.net/Assets/D&D%20Homebrew/index.html
>                                ^
> ```
> Decoding those urls fixes the tests.
> 

Interesting. The docs say that both functions don't work with partially encoded URLs, but I guess the end result in that case is different.  

The pattern I used before for such a scenario was:

1. decode until the URL doesn't change anymore (there are some double-encoded URLs out there)
2. encode the URL once afterwards

**Comment by 4censord** [comment]
Interestingly Uri.EscapeUriString(String) also fails with the url fully encoded:
```
https://thetrove.net/Assets/D%26D%20Homebrew/index.html
                             ^
```

**Pull request merged**
