### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by Wingysam**
Hi! I created a simple Dockerfile which builds and creates a Docker image.

### CODE REVIEW

**Comment by KoalaBear84** [comment]
Just a note.. I really wanted to look at this earlier, but haven't got/took the time to do so. Sorry, I will try to look at it ASAP, I'm really curious about it :)

**Comment by KoalaBear84** [comment]
Do you mean that this way it can be used to directly build it from docker (also)?

https://stackoverflow.com/questions/26753030/how-to-build-docker-image-from-github-repository

I have never really worked with Docker yet.

**Comment by Wingysam** [comment]
You can build and use it with this:
```
root@home:~/OpenDirectoryDownloader# docker build . -t opendirectorydownloader
Sending build context to Docker daemon  4.555MB
Step 1/5 : FROM mcr.microsoft.com/dotnet/core-nightly/sdk:3.0-alpine3.10
 ---> e836bd48b436
Step 2/5 : COPY . /app
 ---> Using cache
 ---> 4e03cb54971f
Step 3/5 : WORKDIR /app
 ---> Using cache
 ---> 69fa2ab9939e
Step 4/5 : RUN dotnet build OpenDirectoryDownloader
 ---> Running in 4846d2c6ba5f
Microsoft (R) Build Engine version 16.3.0-preview-19414-01+bbd9cfeca for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 1.25 sec for /app/OpenDirectoryDownloader.Shared/OpenDirectoryDownloader.Shared.csproj.
  Restore completed in 4 sec for /app/OpenDirectoryDownloader.GoogleDrive/OpenDirectoryDownloader.GoogleDrive.csproj.
  Restore completed in 4.12 sec for /app/OpenDirectoryDownloader/OpenDirectoryDownloader.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  OpenDirectoryDownloader.Shared -> /app/OpenDirectoryDownloader.Shared/bin/Debug/netcoreapp3.0/OpenDirectoryDownloader.Shared.dll
  OpenDirectoryDownloader.GoogleDrive -> /app/OpenDirectoryDownloader.GoogleDrive/bin/Debug/netcoreapp3.0/OpenDirectoryDownloader.GoogleDrive.dll
  OpenDirectoryDownloader -> /app/OpenDirectoryDownloader/bin/Debug/netcoreapp3.0/OpenDirectoryDownloader.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.85
Removing intermediate container 4846d2c6ba5f
 ---> d0c009cbbaac
Step 5/5 : ENTRYPOINT ["./OpenDirectoryDownloader/bin/Debug/netcoreapp3.0/OpenDirectoryDownloader"]
 ---> Running in 2c4a6a17b28c
Removing intermediate container 2c4a6a17b28c
 ---> 79372ba61baf
Successfully built 79372ba61baf
Successfully tagged opendirectorydownloader:latest
root@home:~/OpenDirectoryDownloader# docker run --rm -it opendirectorydownloader
Started
Which URL do you want to index?
```

**Comment by nikhilbhardwaj** [comment]
I'm running this docker container on mac os and it works well.

I do have a question - how do I generate a text file with links from the json file?

The copy to clipboard option fails and saving to json creates a json file in the container.
I'm able to ssh and then copy that file to my main machine.
From the json file I'd like to generate a text file that I can use with aria2c or wget like the project readme says.

Would love to get your input on this @Wingysam

**Comment by Wingysam** [comment]
@nikhilbhardwaj Maybe you can use the -v flag on docker to get the directory that it saves the text file to?

**Comment by KoalaBear84** [comment]
Luckily there are now release for the 3 major runtimes:
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/latest

@Wingysam Could you update this one to .NET Core 3.1? If so, I would like to (finally, I know) test it myself. Kind regards!

**Comment by Wingysam** [comment]
@KoalaBear84 Updated, not sure if it will work, but it should.

**Comment by KoalaBear84** [comment]
I didn't install Docker because of WSL(2), but now I did.

Used my own edited Dockerfile, see above.

I've got the following error, did I broke it?:

```bash
PS C:\Users\UserName> docker build https://raw.githubusercontent.com/KoalaBear84/OpenDirectoryDownloader/d034673e774a94cb08f12514290b37b24d0dc51e/Dockerfile
Downloading build context from remote url: https://raw.githubusercontent.com/KoalaBear84/OpenDirectoryDownloader/d034673Downloading build context from remote url: https://raw.githubusercontent.com/KoalaBear84/OpenDirectoryDownloader/d034673e774a94cb08f12514290b37b24d0dc51e/Dockerfile     220B
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM mcr.microsoft.com/dotnet/core-nightly/sdk:3.1-alpine3.10
3.1-alpine3.10: Pulling from dotnet/core-nightly/sdk
21c83c524219: Pull complete
ca1eceea356d: Pull complete
f089495d09a1: Pull complete
c0cc802dcea3: Pull complete
6a7239022590: Pull complete
78c67e0c8a43: Pull complete
bc9947220524: Pull complete
Digest: sha256:69052602dd24ab9d06264e6dbcb8d11c7087d64474041daa87a94a96a55bb9d8
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core-nightly/sdk:3.1-alpine3.10
 ---> adb8c6fee688
Step 2/5 : COPY . /app
 ---> e5fe86e79667
Step 3/5 : WORKDIR /app
 ---> Running in 43d1fa34a7be
Removing intermediate container 43d1fa34a7be
 ---> f77fbd607a4a
Step 4/5 : RUN dotnet build OpenDirectoryDownloader
 ---> Running in 8960f6d52519
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: OpenDirectoryDownloader
The command '/bin/sh -c dotnet build OpenDirectoryDownloader' returned a non-zero code: 1
```

Or is some path not correct? I don't know how you would test this :)

**Comment by KoalaBear84** [comment]
Thanks @Wingysam  !

Finally got it working, in the post above I guess I was in the wrong folder, so the paths were not correct. Also added it in the readme.

**Pull request merged**
