### PR TITLE
Use current working directory for output files

### LINKED ISSUE #67: Honor CWD (current working directory)
**Describe the bug**

Spawning an ODD process using NodeJS's `spawn` or `exec` commands, while setting the `cwd` options to a specific directory *should* make the process behave as if it was launched from this directory. Instead, it behaves as if it were launched from the folder where the binary is located.  
When I launch the process manually through a command line, it will always behave as if it was launched from the current directory of the command line.

Try looking at the filenames of the output files in both scenarios.

Here should be the relevant part of the code, where the output directory is determined, seemingly by looking at the directory of the binary:
https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/8955599d5103c189f6f0e7ea1585ccde48abff56/OpenDirectoryDownloader/Library.cs#L48

Here's the relevant documentation on the `AppContext.BaseDirectory` property used to set the output directory:
https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-5.0
> the value returned is the containing directory of the host executable.

I honestly have no idea why it works when using the command line. From what I've seen, that shouldn't work either. Maybe some Windows-trickery...

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10 x64, WSL1 (Debian)
 - NodeJS 14.15.1
 - Version: [e.g. 1.0.0.0] 1.9.3.6
 
 
Sorry for bombarding you with issues...
I try to keep them small and I believe it yields results faster than making myself acquainted with .NET, submitting a PR and waiting for you to approve it 😅

Also a disclaimer: I'm not 100% sure this is an issue with ODD (because it behaves correctly using cmd). But looking at your code and the .NET documentation, I am *pretty* sure it is ¯\\\_(ツ)\_/¯

### PR DESCRIPTION
**Pull request by Chaphasilor**
- this closes #67

@KoalaBear84 you might wanna test this a bit, just in case there is some expected behavior that changed because of this...

### CODE REVIEW

**Comment by KoalaBear84** [comment]
If we want to use the CWD, then this should work indeed. I'll just merge it and release a new version.

**Comment by Chaphasilor** [comment]
> If we want to use the CWD, then this should work indeed. I'll just merge it and release a new version.

I'd say it's a lot more intuitive than using the path where the executable is located (which might not even be the case depending on the shell)😉

**Comment by KoalaBear84** [comment]
😮😂

Released: https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.3.8

**Comment by Chaphasilor** [comment]
> Released: https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.3.8

Next PR tomorrow, if I get to it :D

**Pull request merged**
